version: '3.1'
services:
  millionnets-app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    ports:
      - "127.0.0.1:3021:3021"
      - "127.0.0.1:3024:3024"
    depends_on:
      - "millionnets-redis-mndev"
      - "millionnets-postgres-mndev"
    volumes:
      - app-static:/app/app/static
    env_file:
      - production.app.env
  millionnets-timeline:
    build:
      context: .
      dockerfile: docker/timeline.Dockerfile
    ports:
      - "127.0.0.1:3029:3029"
    env_file:
      - production.app.env
  millionnets-redis-mndev:
    image: "redis:5.0-buster"
  millionnets-postgres-mndev:
    image: "postgres:11.4"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - production.app.env
volumes:
  pgdata:
  app-static:
