version: '3.1'
services:
  millionnets-timeline:
    build:
      context: .
      dockerfile: docker/timeline.Dockerfile
    expose:
      - "3029"
    env_file:
      - production.timeline.env
  millionnets-timeline-proxy:
    build: ./timeline-proxy
    ports:
      - "80:80"
    depends_on:
      - "millionnets-timeline"
